# Generated by Django 4.0 on 2023-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pic_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
