# Generated by Django 4.2.2 on 2023-06-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic_model',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
