# Generated by Django 4.2.2 on 2023-06-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_remove_pic_model_url_pic_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic_model',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
